export * from './header';
export * from './get-started';
export * from './services';
export * from './portfolio';
export * from './banner';
export * from './contact-form';
export * from './Information'
export * from './Sponsors';
export * from './Vip';
export * from './Vidoes';
export * from './Events';
export * from './Started';
